package com.scorpion.pojo;

import java.util.Date;

public class bignews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.similarcount
     *
     * @mbggenerated
     */
    private Integer similarcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bignews.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.id
     *
     * @return the value of bignews.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.id
     *
     * @param id the value for bignews.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.name
     *
     * @return the value of bignews.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.name
     *
     * @param name the value for bignews.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.title
     *
     * @return the value of bignews.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.title
     *
     * @param title the value for bignews.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.date
     *
     * @return the value of bignews.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.date
     *
     * @param date the value for bignews.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.url
     *
     * @return the value of bignews.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.url
     *
     * @param url the value for bignews.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.similarcount
     *
     * @return the value of bignews.similarcount
     *
     * @mbggenerated
     */
    public Integer getSimilarcount() {
        return similarcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.similarcount
     *
     * @param similarcount the value for bignews.similarcount
     *
     * @mbggenerated
     */
    public void setSimilarcount(Integer similarcount) {
        this.similarcount = similarcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.keywords
     *
     * @return the value of bignews.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.keywords
     *
     * @param keywords the value for bignews.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bignews.content
     *
     * @return the value of bignews.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bignews.content
     *
     * @param content the value for bignews.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}