package com.scorpion.pojo;

public class ComHealthValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.healthvalue_month
     *
     * @mbggenerated
     */
    private String healthvalueMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.healthvalue_season
     *
     * @mbggenerated
     */
    private String healthvalueSeason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.posnum_month
     *
     * @mbggenerated
     */
    private String posnumMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.posnum_season
     *
     * @mbggenerated
     */
    private String posnumSeason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.negnum_month
     *
     * @mbggenerated
     */
    private String negnumMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.negnum_season
     *
     * @mbggenerated
     */
    private String negnumSeason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comhealth.name
     *
     * @mbggenerated
     */
    private String name;

    private float health_value;

    public float getHealth_value() {
        return health_value;
    }

    public void setHealth_value(float health_value) {
        this.health_value = health_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.id
     *
     * @return the value of comhealth.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.id
     *
     * @param id the value for comhealth.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.healthvalue_month
     *
     * @return the value of comhealth.healthvalue_month
     *
     * @mbggenerated
     */
    public String getHealthvalueMonth() {
        return healthvalueMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.healthvalue_month
     *
     * @param healthvalueMonth the value for comhealth.healthvalue_month
     *
     * @mbggenerated
     */
    public void setHealthvalueMonth(String healthvalueMonth) {
        this.healthvalueMonth = healthvalueMonth == null ? null : healthvalueMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.healthvalue_season
     *
     * @return the value of comhealth.healthvalue_season
     *
     * @mbggenerated
     */
    public String getHealthvalueSeason() {
        return healthvalueSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.healthvalue_season
     *
     * @param healthvalueSeason the value for comhealth.healthvalue_season
     *
     * @mbggenerated
     */
    public void setHealthvalueSeason(String healthvalueSeason) {
        this.healthvalueSeason = healthvalueSeason == null ? null : healthvalueSeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.posnum_month
     *
     * @return the value of comhealth.posnum_month
     *
     * @mbggenerated
     */
    public String getPosnumMonth() {
        return posnumMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.posnum_month
     *
     * @param posnumMonth the value for comhealth.posnum_month
     *
     * @mbggenerated
     */
    public void setPosnumMonth(String posnumMonth) {
        this.posnumMonth = posnumMonth == null ? null : posnumMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.posnum_season
     *
     * @return the value of comhealth.posnum_season
     *
     * @mbggenerated
     */
    public String getPosnumSeason() {
        return posnumSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.posnum_season
     *
     * @param posnumSeason the value for comhealth.posnum_season
     *
     * @mbggenerated
     */
    public void setPosnumSeason(String posnumSeason) {
        this.posnumSeason = posnumSeason == null ? null : posnumSeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.negnum_month
     *
     * @return the value of comhealth.negnum_month
     *
     * @mbggenerated
     */
    public String getNegnumMonth() {
        return negnumMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.negnum_month
     *
     * @param negnumMonth the value for comhealth.negnum_month
     *
     * @mbggenerated
     */
    public void setNegnumMonth(String negnumMonth) {
        this.negnumMonth = negnumMonth == null ? null : negnumMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.negnum_season
     *
     * @return the value of comhealth.negnum_season
     *
     * @mbggenerated
     */
    public String getNegnumSeason() {
        return negnumSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.negnum_season
     *
     * @param negnumSeason the value for comhealth.negnum_season
     *
     * @mbggenerated
     */
    public void setNegnumSeason(String negnumSeason) {
        this.negnumSeason = negnumSeason == null ? null : negnumSeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comhealth.name
     *
     * @return the value of comhealth.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comhealth.name
     *
     * @param name the value for comhealth.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}