package com.scorpion.pojo;

import java.util.ArrayList;
import java.util.List;

public class companyinformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public companyinformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumIsNull() {
            addCriterion("lastmonthsum is null");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumIsNotNull() {
            addCriterion("lastmonthsum is not null");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumEqualTo(Integer value) {
            addCriterion("lastmonthsum =", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumNotEqualTo(Integer value) {
            addCriterion("lastmonthsum <>", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumGreaterThan(Integer value) {
            addCriterion("lastmonthsum >", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastmonthsum >=", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumLessThan(Integer value) {
            addCriterion("lastmonthsum <", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumLessThanOrEqualTo(Integer value) {
            addCriterion("lastmonthsum <=", value, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumIn(List<Integer> values) {
            addCriterion("lastmonthsum in", values, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumNotIn(List<Integer> values) {
            addCriterion("lastmonthsum not in", values, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumBetween(Integer value1, Integer value2) {
            addCriterion("lastmonthsum between", value1, value2, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthsumNotBetween(Integer value1, Integer value2) {
            addCriterion("lastmonthsum not between", value1, value2, "lastmonthsum");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegIsNull() {
            addCriterion("lastmonthneg is null");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegIsNotNull() {
            addCriterion("lastmonthneg is not null");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegEqualTo(Integer value) {
            addCriterion("lastmonthneg =", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegNotEqualTo(Integer value) {
            addCriterion("lastmonthneg <>", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegGreaterThan(Integer value) {
            addCriterion("lastmonthneg >", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastmonthneg >=", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegLessThan(Integer value) {
            addCriterion("lastmonthneg <", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegLessThanOrEqualTo(Integer value) {
            addCriterion("lastmonthneg <=", value, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegIn(List<Integer> values) {
            addCriterion("lastmonthneg in", values, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegNotIn(List<Integer> values) {
            addCriterion("lastmonthneg not in", values, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegBetween(Integer value1, Integer value2) {
            addCriterion("lastmonthneg between", value1, value2, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andLastmonthnegNotBetween(Integer value1, Integer value2) {
            addCriterion("lastmonthneg not between", value1, value2, "lastmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumIsNull() {
            addCriterion("curmonthsum is null");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumIsNotNull() {
            addCriterion("curmonthsum is not null");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumEqualTo(Integer value) {
            addCriterion("curmonthsum =", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumNotEqualTo(Integer value) {
            addCriterion("curmonthsum <>", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumGreaterThan(Integer value) {
            addCriterion("curmonthsum >", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumGreaterThanOrEqualTo(Integer value) {
            addCriterion("curmonthsum >=", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumLessThan(Integer value) {
            addCriterion("curmonthsum <", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumLessThanOrEqualTo(Integer value) {
            addCriterion("curmonthsum <=", value, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumIn(List<Integer> values) {
            addCriterion("curmonthsum in", values, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumNotIn(List<Integer> values) {
            addCriterion("curmonthsum not in", values, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumBetween(Integer value1, Integer value2) {
            addCriterion("curmonthsum between", value1, value2, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthsumNotBetween(Integer value1, Integer value2) {
            addCriterion("curmonthsum not between", value1, value2, "curmonthsum");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegIsNull() {
            addCriterion("curmonthneg is null");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegIsNotNull() {
            addCriterion("curmonthneg is not null");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegEqualTo(Integer value) {
            addCriterion("curmonthneg =", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegNotEqualTo(Integer value) {
            addCriterion("curmonthneg <>", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegGreaterThan(Integer value) {
            addCriterion("curmonthneg >", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegGreaterThanOrEqualTo(Integer value) {
            addCriterion("curmonthneg >=", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegLessThan(Integer value) {
            addCriterion("curmonthneg <", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegLessThanOrEqualTo(Integer value) {
            addCriterion("curmonthneg <=", value, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegIn(List<Integer> values) {
            addCriterion("curmonthneg in", values, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegNotIn(List<Integer> values) {
            addCriterion("curmonthneg not in", values, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegBetween(Integer value1, Integer value2) {
            addCriterion("curmonthneg between", value1, value2, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurmonthnegNotBetween(Integer value1, Integer value2) {
            addCriterion("curmonthneg not between", value1, value2, "curmonthneg");
            return (Criteria) this;
        }

        public Criteria andCurhealthIsNull() {
            addCriterion("curhealth is null");
            return (Criteria) this;
        }

        public Criteria andCurhealthIsNotNull() {
            addCriterion("curhealth is not null");
            return (Criteria) this;
        }

        public Criteria andCurhealthEqualTo(Float value) {
            addCriterion("curhealth =", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthNotEqualTo(Float value) {
            addCriterion("curhealth <>", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthGreaterThan(Float value) {
            addCriterion("curhealth >", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthGreaterThanOrEqualTo(Float value) {
            addCriterion("curhealth >=", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthLessThan(Float value) {
            addCriterion("curhealth <", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthLessThanOrEqualTo(Float value) {
            addCriterion("curhealth <=", value, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthIn(List<Float> values) {
            addCriterion("curhealth in", values, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthNotIn(List<Float> values) {
            addCriterion("curhealth not in", values, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthBetween(Float value1, Float value2) {
            addCriterion("curhealth between", value1, value2, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurhealthNotBetween(Float value1, Float value2) {
            addCriterion("curhealth not between", value1, value2, "curhealth");
            return (Criteria) this;
        }

        public Criteria andCurreputationIsNull() {
            addCriterion("curreputation is null");
            return (Criteria) this;
        }

        public Criteria andCurreputationIsNotNull() {
            addCriterion("curreputation is not null");
            return (Criteria) this;
        }

        public Criteria andCurreputationEqualTo(Float value) {
            addCriterion("curreputation =", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationNotEqualTo(Float value) {
            addCriterion("curreputation <>", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationGreaterThan(Float value) {
            addCriterion("curreputation >", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationGreaterThanOrEqualTo(Float value) {
            addCriterion("curreputation >=", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationLessThan(Float value) {
            addCriterion("curreputation <", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationLessThanOrEqualTo(Float value) {
            addCriterion("curreputation <=", value, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationIn(List<Float> values) {
            addCriterion("curreputation in", values, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationNotIn(List<Float> values) {
            addCriterion("curreputation not in", values, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationBetween(Float value1, Float value2) {
            addCriterion("curreputation between", value1, value2, "curreputation");
            return (Criteria) this;
        }

        public Criteria andCurreputationNotBetween(Float value1, Float value2) {
            addCriterion("curreputation not between", value1, value2, "curreputation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companyinformation
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}