package com.scorpion.pojo;

public class companyinformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.lastmonthsum
     *
     * @mbggenerated
     */
    private Integer lastmonthsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.lastmonthneg
     *
     * @mbggenerated
     */
    private Integer lastmonthneg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.curmonthsum
     *
     * @mbggenerated
     */
    private Integer curmonthsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.curmonthneg
     *
     * @mbggenerated
     */
    private Integer curmonthneg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.curhealth
     *
     * @mbggenerated
     */
    private Float curhealth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.curreputation
     *
     * @mbggenerated
     */
    private Float curreputation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinformation.hotword
     *
     * @mbggenerated
     */
    private String hotword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.id
     *
     * @return the value of companyinformation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.id
     *
     * @param id the value for companyinformation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.name
     *
     * @return the value of companyinformation.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.name
     *
     * @param name the value for companyinformation.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.lastmonthsum
     *
     * @return the value of companyinformation.lastmonthsum
     *
     * @mbggenerated
     */
    public Integer getLastmonthsum() {
        return lastmonthsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.lastmonthsum
     *
     * @param lastmonthsum the value for companyinformation.lastmonthsum
     *
     * @mbggenerated
     */
    public void setLastmonthsum(Integer lastmonthsum) {
        this.lastmonthsum = lastmonthsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.lastmonthneg
     *
     * @return the value of companyinformation.lastmonthneg
     *
     * @mbggenerated
     */
    public Integer getLastmonthneg() {
        return lastmonthneg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.lastmonthneg
     *
     * @param lastmonthneg the value for companyinformation.lastmonthneg
     *
     * @mbggenerated
     */
    public void setLastmonthneg(Integer lastmonthneg) {
        this.lastmonthneg = lastmonthneg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.curmonthsum
     *
     * @return the value of companyinformation.curmonthsum
     *
     * @mbggenerated
     */
    public Integer getCurmonthsum() {
        return curmonthsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.curmonthsum
     *
     * @param curmonthsum the value for companyinformation.curmonthsum
     *
     * @mbggenerated
     */
    public void setCurmonthsum(Integer curmonthsum) {
        this.curmonthsum = curmonthsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.curmonthneg
     *
     * @return the value of companyinformation.curmonthneg
     *
     * @mbggenerated
     */
    public Integer getCurmonthneg() {
        return curmonthneg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.curmonthneg
     *
     * @param curmonthneg the value for companyinformation.curmonthneg
     *
     * @mbggenerated
     */
    public void setCurmonthneg(Integer curmonthneg) {
        this.curmonthneg = curmonthneg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.curhealth
     *
     * @return the value of companyinformation.curhealth
     *
     * @mbggenerated
     */
    public Float getCurhealth() {
        return curhealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.curhealth
     *
     * @param curhealth the value for companyinformation.curhealth
     *
     * @mbggenerated
     */
    public void setCurhealth(Float curhealth) {
        this.curhealth = curhealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.curreputation
     *
     * @return the value of companyinformation.curreputation
     *
     * @mbggenerated
     */
    public Float getCurreputation() {
        return curreputation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.curreputation
     *
     * @param curreputation the value for companyinformation.curreputation
     *
     * @mbggenerated
     */
    public void setCurreputation(Float curreputation) {
        this.curreputation = curreputation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinformation.hotword
     *
     * @return the value of companyinformation.hotword
     *
     * @mbggenerated
     */
    public String getHotword() {
        return hotword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinformation.hotword
     *
     * @param hotword the value for companyinformation.hotword
     *
     * @mbggenerated
     */
    public void setHotword(String hotword) {
        this.hotword = hotword == null ? null : hotword.trim();
    }
}