package com.scorpion.pojo;

import java.util.Date;

public class copper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.opening
     *
     * @mbggenerated
     */
    private Float opening;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.highPrice
     *
     * @mbggenerated
     */
    private Float highprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.lowPrice
     *
     * @mbggenerated
     */
    private Float lowprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.settlement
     *
     * @mbggenerated
     */
    private Float settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.ups_and_downs
     *
     * @mbggenerated
     */
    private Float upsAndDowns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copper.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.id
     *
     * @return the value of copper.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.id
     *
     * @param id the value for copper.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.opening
     *
     * @return the value of copper.opening
     *
     * @mbggenerated
     */
    public Float getOpening() {
        return opening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.opening
     *
     * @param opening the value for copper.opening
     *
     * @mbggenerated
     */
    public void setOpening(Float opening) {
        this.opening = opening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.highPrice
     *
     * @return the value of copper.highPrice
     *
     * @mbggenerated
     */
    public Float getHighprice() {
        return highprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.highPrice
     *
     * @param highprice the value for copper.highPrice
     *
     * @mbggenerated
     */
    public void setHighprice(Float highprice) {
        this.highprice = highprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.lowPrice
     *
     * @return the value of copper.lowPrice
     *
     * @mbggenerated
     */
    public Float getLowprice() {
        return lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.lowPrice
     *
     * @param lowprice the value for copper.lowPrice
     *
     * @mbggenerated
     */
    public void setLowprice(Float lowprice) {
        this.lowprice = lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.settlement
     *
     * @return the value of copper.settlement
     *
     * @mbggenerated
     */
    public Float getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.settlement
     *
     * @param settlement the value for copper.settlement
     *
     * @mbggenerated
     */
    public void setSettlement(Float settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.ups_and_downs
     *
     * @return the value of copper.ups_and_downs
     *
     * @mbggenerated
     */
    public Float getUpsAndDowns() {
        return upsAndDowns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.ups_and_downs
     *
     * @param upsAndDowns the value for copper.ups_and_downs
     *
     * @mbggenerated
     */
    public void setUpsAndDowns(Float upsAndDowns) {
        this.upsAndDowns = upsAndDowns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copper.date
     *
     * @return the value of copper.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copper.date
     *
     * @param date the value for copper.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}