package com.scorpion.pojo;

public class crude_wti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.ups_and_downs
     *
     * @mbggenerated
     */
    private String upsAndDowns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.ups_and_downs_l
     *
     * @mbggenerated
     */
    private String upsAndDownsL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crude_wti.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.id
     *
     * @return the value of crude_wti.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.id
     *
     * @param id the value for crude_wti.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.name
     *
     * @return the value of crude_wti.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.name
     *
     * @param name the value for crude_wti.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.price
     *
     * @return the value of crude_wti.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.price
     *
     * @param price the value for crude_wti.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.ups_and_downs
     *
     * @return the value of crude_wti.ups_and_downs
     *
     * @mbggenerated
     */
    public String getUpsAndDowns() {
        return upsAndDowns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.ups_and_downs
     *
     * @param upsAndDowns the value for crude_wti.ups_and_downs
     *
     * @mbggenerated
     */
    public void setUpsAndDowns(String upsAndDowns) {
        this.upsAndDowns = upsAndDowns == null ? null : upsAndDowns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.ups_and_downs_l
     *
     * @return the value of crude_wti.ups_and_downs_l
     *
     * @mbggenerated
     */
    public String getUpsAndDownsL() {
        return upsAndDownsL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.ups_and_downs_l
     *
     * @param upsAndDownsL the value for crude_wti.ups_and_downs_l
     *
     * @mbggenerated
     */
    public void setUpsAndDownsL(String upsAndDownsL) {
        this.upsAndDownsL = upsAndDownsL == null ? null : upsAndDownsL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crude_wti.date
     *
     * @return the value of crude_wti.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crude_wti.date
     *
     * @param date the value for crude_wti.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}