package com.scorpion.pojo;

public class democompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column democompany.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column democompany.curreputation
     *
     * @mbggenerated
     */
    private Float curreputation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column democompany.company_name
     *
     * @return the value of democompany.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column democompany.company_name
     *
     * @param companyName the value for democompany.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column democompany.curreputation
     *
     * @return the value of democompany.curreputation
     *
     * @mbggenerated
     */
    public Float getCurreputation() {
        return curreputation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column democompany.curreputation
     *
     * @param curreputation the value for democompany.curreputation
     *
     * @mbggenerated
     */
    public void setCurreputation(Float curreputation) {
        this.curreputation = curreputation;
    }
}