package com.scorpion.pojo;

public class dollar_exchange_rate_of_rmb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.dollar
     *
     * @mbggenerated
     */
    private String dollar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Euro
     *
     * @mbggenerated
     */
    private String euro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.yen
     *
     * @mbggenerated
     */
    private String yen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.HongKongDollar
     *
     * @mbggenerated
     */
    private String hongkongdollar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.pound
     *
     * @mbggenerated
     */
    private String pound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.myr
     *
     * @mbggenerated
     */
    private String myr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Rouble
     *
     * @mbggenerated
     */
    private String rouble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Rand
     *
     * @mbggenerated
     */
    private String rand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.SouthKoreanWon
     *
     * @mbggenerated
     */
    private String southkoreanwon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Riyal
     *
     * @mbggenerated
     */
    private String riyal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Flynn
     *
     * @mbggenerated
     */
    private String flynn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.ZL
     *
     * @mbggenerated
     */
    private String zl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.dkk
     *
     * @mbggenerated
     */
    private String dkk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.SwedishKrona
     *
     * @mbggenerated
     */
    private String swedishkrona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.NorwayKrone
     *
     * @mbggenerated
     */
    private String norwaykrone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Lira
     *
     * @mbggenerated
     */
    private String lira;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.peso
     *
     * @mbggenerated
     */
    private String peso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.TheAustraliandollar
     *
     * @mbggenerated
     */
    private String theaustraliandollar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Cad
     *
     * @mbggenerated
     */
    private String cad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.NewZealand
     *
     * @mbggenerated
     */
    private String newzealand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.Singapored
     *
     * @mbggenerated
     */
    private String singapored;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.SwissFranc
     *
     * @mbggenerated
     */
    private String swissfranc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.date
     *
     * @return the value of dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.date
     *
     * @param date the value for dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.dollar
     *
     * @return the value of dollar_exchange_rate_of_rmb.dollar
     *
     * @mbggenerated
     */
    public String getDollar() {
        return dollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.dollar
     *
     * @param dollar the value for dollar_exchange_rate_of_rmb.dollar
     *
     * @mbggenerated
     */
    public void setDollar(String dollar) {
        this.dollar = dollar == null ? null : dollar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Euro
     *
     * @return the value of dollar_exchange_rate_of_rmb.Euro
     *
     * @mbggenerated
     */
    public String getEuro() {
        return euro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Euro
     *
     * @param euro the value for dollar_exchange_rate_of_rmb.Euro
     *
     * @mbggenerated
     */
    public void setEuro(String euro) {
        this.euro = euro == null ? null : euro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.yen
     *
     * @return the value of dollar_exchange_rate_of_rmb.yen
     *
     * @mbggenerated
     */
    public String getYen() {
        return yen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.yen
     *
     * @param yen the value for dollar_exchange_rate_of_rmb.yen
     *
     * @mbggenerated
     */
    public void setYen(String yen) {
        this.yen = yen == null ? null : yen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.HongKongDollar
     *
     * @return the value of dollar_exchange_rate_of_rmb.HongKongDollar
     *
     * @mbggenerated
     */
    public String getHongkongdollar() {
        return hongkongdollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.HongKongDollar
     *
     * @param hongkongdollar the value for dollar_exchange_rate_of_rmb.HongKongDollar
     *
     * @mbggenerated
     */
    public void setHongkongdollar(String hongkongdollar) {
        this.hongkongdollar = hongkongdollar == null ? null : hongkongdollar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.pound
     *
     * @return the value of dollar_exchange_rate_of_rmb.pound
     *
     * @mbggenerated
     */
    public String getPound() {
        return pound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.pound
     *
     * @param pound the value for dollar_exchange_rate_of_rmb.pound
     *
     * @mbggenerated
     */
    public void setPound(String pound) {
        this.pound = pound == null ? null : pound.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.myr
     *
     * @return the value of dollar_exchange_rate_of_rmb.myr
     *
     * @mbggenerated
     */
    public String getMyr() {
        return myr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.myr
     *
     * @param myr the value for dollar_exchange_rate_of_rmb.myr
     *
     * @mbggenerated
     */
    public void setMyr(String myr) {
        this.myr = myr == null ? null : myr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Rouble
     *
     * @return the value of dollar_exchange_rate_of_rmb.Rouble
     *
     * @mbggenerated
     */
    public String getRouble() {
        return rouble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Rouble
     *
     * @param rouble the value for dollar_exchange_rate_of_rmb.Rouble
     *
     * @mbggenerated
     */
    public void setRouble(String rouble) {
        this.rouble = rouble == null ? null : rouble.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Rand
     *
     * @return the value of dollar_exchange_rate_of_rmb.Rand
     *
     * @mbggenerated
     */
    public String getRand() {
        return rand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Rand
     *
     * @param rand the value for dollar_exchange_rate_of_rmb.Rand
     *
     * @mbggenerated
     */
    public void setRand(String rand) {
        this.rand = rand == null ? null : rand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.SouthKoreanWon
     *
     * @return the value of dollar_exchange_rate_of_rmb.SouthKoreanWon
     *
     * @mbggenerated
     */
    public String getSouthkoreanwon() {
        return southkoreanwon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.SouthKoreanWon
     *
     * @param southkoreanwon the value for dollar_exchange_rate_of_rmb.SouthKoreanWon
     *
     * @mbggenerated
     */
    public void setSouthkoreanwon(String southkoreanwon) {
        this.southkoreanwon = southkoreanwon == null ? null : southkoreanwon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.dir
     *
     * @return the value of dollar_exchange_rate_of_rmb.dir
     *
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.dir
     *
     * @param dir the value for dollar_exchange_rate_of_rmb.dir
     *
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Riyal
     *
     * @return the value of dollar_exchange_rate_of_rmb.Riyal
     *
     * @mbggenerated
     */
    public String getRiyal() {
        return riyal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Riyal
     *
     * @param riyal the value for dollar_exchange_rate_of_rmb.Riyal
     *
     * @mbggenerated
     */
    public void setRiyal(String riyal) {
        this.riyal = riyal == null ? null : riyal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Flynn
     *
     * @return the value of dollar_exchange_rate_of_rmb.Flynn
     *
     * @mbggenerated
     */
    public String getFlynn() {
        return flynn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Flynn
     *
     * @param flynn the value for dollar_exchange_rate_of_rmb.Flynn
     *
     * @mbggenerated
     */
    public void setFlynn(String flynn) {
        this.flynn = flynn == null ? null : flynn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.ZL
     *
     * @return the value of dollar_exchange_rate_of_rmb.ZL
     *
     * @mbggenerated
     */
    public String getZl() {
        return zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.ZL
     *
     * @param zl the value for dollar_exchange_rate_of_rmb.ZL
     *
     * @mbggenerated
     */
    public void setZl(String zl) {
        this.zl = zl == null ? null : zl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.dkk
     *
     * @return the value of dollar_exchange_rate_of_rmb.dkk
     *
     * @mbggenerated
     */
    public String getDkk() {
        return dkk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.dkk
     *
     * @param dkk the value for dollar_exchange_rate_of_rmb.dkk
     *
     * @mbggenerated
     */
    public void setDkk(String dkk) {
        this.dkk = dkk == null ? null : dkk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.SwedishKrona
     *
     * @return the value of dollar_exchange_rate_of_rmb.SwedishKrona
     *
     * @mbggenerated
     */
    public String getSwedishkrona() {
        return swedishkrona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.SwedishKrona
     *
     * @param swedishkrona the value for dollar_exchange_rate_of_rmb.SwedishKrona
     *
     * @mbggenerated
     */
    public void setSwedishkrona(String swedishkrona) {
        this.swedishkrona = swedishkrona == null ? null : swedishkrona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.NorwayKrone
     *
     * @return the value of dollar_exchange_rate_of_rmb.NorwayKrone
     *
     * @mbggenerated
     */
    public String getNorwaykrone() {
        return norwaykrone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.NorwayKrone
     *
     * @param norwaykrone the value for dollar_exchange_rate_of_rmb.NorwayKrone
     *
     * @mbggenerated
     */
    public void setNorwaykrone(String norwaykrone) {
        this.norwaykrone = norwaykrone == null ? null : norwaykrone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Lira
     *
     * @return the value of dollar_exchange_rate_of_rmb.Lira
     *
     * @mbggenerated
     */
    public String getLira() {
        return lira;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Lira
     *
     * @param lira the value for dollar_exchange_rate_of_rmb.Lira
     *
     * @mbggenerated
     */
    public void setLira(String lira) {
        this.lira = lira == null ? null : lira.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.peso
     *
     * @return the value of dollar_exchange_rate_of_rmb.peso
     *
     * @mbggenerated
     */
    public String getPeso() {
        return peso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.peso
     *
     * @param peso the value for dollar_exchange_rate_of_rmb.peso
     *
     * @mbggenerated
     */
    public void setPeso(String peso) {
        this.peso = peso == null ? null : peso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.TheAustraliandollar
     *
     * @return the value of dollar_exchange_rate_of_rmb.TheAustraliandollar
     *
     * @mbggenerated
     */
    public String getTheaustraliandollar() {
        return theaustraliandollar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.TheAustraliandollar
     *
     * @param theaustraliandollar the value for dollar_exchange_rate_of_rmb.TheAustraliandollar
     *
     * @mbggenerated
     */
    public void setTheaustraliandollar(String theaustraliandollar) {
        this.theaustraliandollar = theaustraliandollar == null ? null : theaustraliandollar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Cad
     *
     * @return the value of dollar_exchange_rate_of_rmb.Cad
     *
     * @mbggenerated
     */
    public String getCad() {
        return cad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Cad
     *
     * @param cad the value for dollar_exchange_rate_of_rmb.Cad
     *
     * @mbggenerated
     */
    public void setCad(String cad) {
        this.cad = cad == null ? null : cad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.NewZealand
     *
     * @return the value of dollar_exchange_rate_of_rmb.NewZealand
     *
     * @mbggenerated
     */
    public String getNewzealand() {
        return newzealand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.NewZealand
     *
     * @param newzealand the value for dollar_exchange_rate_of_rmb.NewZealand
     *
     * @mbggenerated
     */
    public void setNewzealand(String newzealand) {
        this.newzealand = newzealand == null ? null : newzealand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.Singapored
     *
     * @return the value of dollar_exchange_rate_of_rmb.Singapored
     *
     * @mbggenerated
     */
    public String getSingapored() {
        return singapored;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.Singapored
     *
     * @param singapored the value for dollar_exchange_rate_of_rmb.Singapored
     *
     * @mbggenerated
     */
    public void setSingapored(String singapored) {
        this.singapored = singapored == null ? null : singapored.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.SwissFranc
     *
     * @return the value of dollar_exchange_rate_of_rmb.SwissFranc
     *
     * @mbggenerated
     */
    public String getSwissfranc() {
        return swissfranc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.SwissFranc
     *
     * @param swissfranc the value for dollar_exchange_rate_of_rmb.SwissFranc
     *
     * @mbggenerated
     */
    public void setSwissfranc(String swissfranc) {
        this.swissfranc = swissfranc == null ? null : swissfranc.trim();
    }
}