package com.scorpion.pojo;

import java.util.Date;

public class dollar_exchange_rate_of_rmb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.opening
     *
     * @mbggenerated
     */
    private Float opening;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.peak
     *
     * @mbggenerated
     */
    private Float peak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.lowest
     *
     * @mbggenerated
     */
    private Float lowest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.settlement
     *
     * @mbggenerated
     */
    private Float settlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.id
     *
     * @return the value of dollar_exchange_rate_of_rmb.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.id
     *
     * @param id the value for dollar_exchange_rate_of_rmb.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.opening
     *
     * @return the value of dollar_exchange_rate_of_rmb.opening
     *
     * @mbggenerated
     */
    public Float getOpening() {
        return opening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.opening
     *
     * @param opening the value for dollar_exchange_rate_of_rmb.opening
     *
     * @mbggenerated
     */
    public void setOpening(Float opening) {
        this.opening = opening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.peak
     *
     * @return the value of dollar_exchange_rate_of_rmb.peak
     *
     * @mbggenerated
     */
    public Float getPeak() {
        return peak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.peak
     *
     * @param peak the value for dollar_exchange_rate_of_rmb.peak
     *
     * @mbggenerated
     */
    public void setPeak(Float peak) {
        this.peak = peak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.lowest
     *
     * @return the value of dollar_exchange_rate_of_rmb.lowest
     *
     * @mbggenerated
     */
    public Float getLowest() {
        return lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.lowest
     *
     * @param lowest the value for dollar_exchange_rate_of_rmb.lowest
     *
     * @mbggenerated
     */
    public void setLowest(Float lowest) {
        this.lowest = lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.settlement
     *
     * @return the value of dollar_exchange_rate_of_rmb.settlement
     *
     * @mbggenerated
     */
    public Float getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.settlement
     *
     * @param settlement the value for dollar_exchange_rate_of_rmb.settlement
     *
     * @mbggenerated
     */
    public void setSettlement(Float settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dollar_exchange_rate_of_rmb.date
     *
     * @return the value of dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dollar_exchange_rate_of_rmb.date
     *
     * @param date the value for dollar_exchange_rate_of_rmb.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}