package com.scorpion.pojo;

public class IndicateOfPPI {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.indicate
     *
     * @mbggenerated
     */
    private String indicate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.season
     *
     * @mbggenerated
     */
    private String season;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ppi.season_name
     *
     * @mbggenerated
     */
    private String seasonName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.id
     *
     * @return the value of ppi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.id
     *
     * @param id the value for ppi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.area
     *
     * @return the value of ppi.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.area
     *
     * @param area the value for ppi.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.indicate
     *
     * @return the value of ppi.indicate
     *
     * @mbggenerated
     */
    public String getIndicate() {
        return indicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.indicate
     *
     * @param indicate the value for ppi.indicate
     *
     * @mbggenerated
     */
    public void setIndicate(String indicate) {
        this.indicate = indicate == null ? null : indicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.season
     *
     * @return the value of ppi.season
     *
     * @mbggenerated
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.season
     *
     * @param season the value for ppi.season
     *
     * @mbggenerated
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.data
     *
     * @return the value of ppi.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.data
     *
     * @param data the value for ppi.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ppi.season_name
     *
     * @return the value of ppi.season_name
     *
     * @mbggenerated
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ppi.season_name
     *
     * @param seasonName the value for ppi.season_name
     *
     * @mbggenerated
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }
}