package com.scorpion.pojo;

public class IndicateOfExportImport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.indicate
     *
     * @mbggenerated
     */
    private String indicate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.season
     *
     * @mbggenerated
     */
    private String season;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_import.season_name
     *
     * @mbggenerated
     */
    private String seasonName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.id
     *
     * @return the value of export_import.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.id
     *
     * @param id the value for export_import.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.area
     *
     * @return the value of export_import.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.area
     *
     * @param area the value for export_import.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.indicate
     *
     * @return the value of export_import.indicate
     *
     * @mbggenerated
     */
    public String getIndicate() {
        return indicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.indicate
     *
     * @param indicate the value for export_import.indicate
     *
     * @mbggenerated
     */
    public void setIndicate(String indicate) {
        this.indicate = indicate == null ? null : indicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.season
     *
     * @return the value of export_import.season
     *
     * @mbggenerated
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.season
     *
     * @param season the value for export_import.season
     *
     * @mbggenerated
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.data
     *
     * @return the value of export_import.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.data
     *
     * @param data the value for export_import.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_import.season_name
     *
     * @return the value of export_import.season_name
     *
     * @mbggenerated
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_import.season_name
     *
     * @param seasonName the value for export_import.season_name
     *
     * @mbggenerated
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }
}