package com.scorpion.pojo;

public class IndicateOfCPI {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.indicate
     *
     * @mbggenerated
     */
    private String indicate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.season
     *
     * @mbggenerated
     */
    private String season;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cpi.season_name
     *
     * @mbggenerated
     */
    private String seasonName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.id
     *
     * @return the value of cpi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.id
     *
     * @param id the value for cpi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.area
     *
     * @return the value of cpi.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.area
     *
     * @param area the value for cpi.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.indicate
     *
     * @return the value of cpi.indicate
     *
     * @mbggenerated
     */
    public String getIndicate() {
        return indicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.indicate
     *
     * @param indicate the value for cpi.indicate
     *
     * @mbggenerated
     */
    public void setIndicate(String indicate) {
        this.indicate = indicate == null ? null : indicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.season
     *
     * @return the value of cpi.season
     *
     * @mbggenerated
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.season
     *
     * @param season the value for cpi.season
     *
     * @mbggenerated
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.data
     *
     * @return the value of cpi.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.data
     *
     * @param data the value for cpi.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cpi.season_name
     *
     * @return the value of cpi.season_name
     *
     * @mbggenerated
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cpi.season_name
     *
     * @param seasonName the value for cpi.season_name
     *
     * @mbggenerated
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }
}