package com.scorpion.pojo;

import java.util.Date;

public class negativenews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.oreitationvalue
     *
     * @mbggenerated
     */
    private Float oreitationvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.ispush
     *
     * @mbggenerated
     */
    private Integer ispush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column negativenews.isread
     *
     * @mbggenerated
     */
    private Integer isread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.id
     *
     * @return the value of negativenews.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.id
     *
     * @param id the value for negativenews.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.source
     *
     * @return the value of negativenews.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.source
     *
     * @param source the value for negativenews.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.date
     *
     * @return the value of negativenews.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.date
     *
     * @param date the value for negativenews.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.oreitationvalue
     *
     * @return the value of negativenews.oreitationvalue
     *
     * @mbggenerated
     */
    public Float getOreitationvalue() {
        return oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.oreitationvalue
     *
     * @param oreitationvalue the value for negativenews.oreitationvalue
     *
     * @mbggenerated
     */
    public void setOreitationvalue(Float oreitationvalue) {
        this.oreitationvalue = oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.ispush
     *
     * @return the value of negativenews.ispush
     *
     * @mbggenerated
     */
    public Integer getIspush() {
        return ispush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.ispush
     *
     * @param ispush the value for negativenews.ispush
     *
     * @mbggenerated
     */
    public void setIspush(Integer ispush) {
        this.ispush = ispush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column negativenews.isread
     *
     * @return the value of negativenews.isread
     *
     * @mbggenerated
     */
    public Integer getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column negativenews.isread
     *
     * @param isread the value for negativenews.isread
     *
     * @mbggenerated
     */
    public void setIsread(Integer isread) {
        this.isread = isread;
    }
}