package com.scorpion.pojo;

import java.util.Date;

public class NewsOfTopCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.id
     *
     * @mbggenerated
     */
    private Integer id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.oreitation
     *
     * @mbggenerated
     */
    private Integer oreitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topcompany.oreitationvalue
     *
     * @mbggenerated
     */
    private Float oreitationvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.id
     *
     * @return the value of topcompany.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.id
     *
     * @param id the value for topcompany.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.category
     *
     * @return the value of topcompany.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.category
     *
     * @param category the value for topcompany.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.source
     *
     * @return the value of topcompany.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.source
     *
     * @param source the value for topcompany.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.count
     *
     * @return the value of topcompany.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.count
     *
     * @param count the value for topcompany.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.flag
     *
     * @return the value of topcompany.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.flag
     *
     * @param flag the value for topcompany.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.oreitation
     *
     * @return the value of topcompany.oreitation
     *
     * @mbggenerated
     */
    public Integer getOreitation() {
        return oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.oreitation
     *
     * @param oreitation the value for topcompany.oreitation
     *
     * @mbggenerated
     */
    public void setOreitation(Integer oreitation) {
        this.oreitation = oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.topic
     *
     * @return the value of topcompany.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.topic
     *
     * @param topic the value for topcompany.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topcompany.oreitationvalue
     *
     * @return the value of topcompany.oreitationvalue
     *
     * @mbggenerated
     */
    public Float getOreitationvalue() {
        return oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topcompany.oreitationvalue
     *
     * @param oreitationvalue the value for topcompany.oreitationvalue
     *
     * @mbggenerated
     */
    public void setOreitationvalue(Float oreitationvalue) {
        this.oreitationvalue = oreitationvalue;
    }
}