package com.scorpion.pojo;

import java.util.Date;

public class NewsOfCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.date
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.oreitation
     *
     * @mbggenerated
     */
    private Integer oreitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content.oreitationvalue
     *
     * @mbggenerated
     */
    private Float oreitationvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.id
     *
     * @return the value of tb_content.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.id
     *
     * @param id the value for tb_content.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.date
     *
     * @return the value of tb_content.date
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.date
     *
     * @param date the value for tb_content.date
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.category
     *
     * @return the value of tb_content.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.category
     *
     * @param category the value for tb_content.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.source
     *
     * @return the value of tb_content.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.source
     *
     * @param source the value for tb_content.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.count
     *
     * @return the value of tb_content.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.count
     *
     * @param count the value for tb_content.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.flag
     *
     * @return the value of tb_content.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.flag
     *
     * @param flag the value for tb_content.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.oreitation
     *
     * @return the value of tb_content.oreitation
     *
     * @mbggenerated
     */
    public Integer getOreitation() {
        return oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.oreitation
     *
     * @param oreitation the value for tb_content.oreitation
     *
     * @mbggenerated
     */
    public void setOreitation(Integer oreitation) {
        this.oreitation = oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.topic
     *
     * @return the value of tb_content.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.topic
     *
     * @param topic the value for tb_content.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content.oreitationvalue
     *
     * @return the value of tb_content.oreitationvalue
     *
     * @mbggenerated
     */
    public Float getOreitationvalue() {
        return oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content.oreitationvalue
     *
     * @param oreitationvalue the value for tb_content.oreitationvalue
     *
     * @mbggenerated
     */
    public void setOreitationvalue(Float oreitationvalue) {
        this.oreitationvalue = oreitationvalue;
    }
}