package com.scorpion.pojo;

import java.util.Date;

public class Pmi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmi.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmi.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmi.pmivalues
     *
     * @mbggenerated
     */
    private Float pmivalues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmi.id
     *
     * @return the value of pmi.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmi.id
     *
     * @param id the value for pmi.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmi.date
     *
     * @return the value of pmi.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmi.date
     *
     * @param date the value for pmi.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmi.pmivalues
     *
     * @return the value of pmi.pmivalues
     *
     * @mbggenerated
     */
    public Float getPmivalues() {
        return pmivalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmi.pmivalues
     *
     * @param pmivalues the value for pmi.pmivalues
     *
     * @mbggenerated
     */
    public void setPmivalues(Float pmivalues) {
        this.pmivalues = pmivalues;
    }


}