package com.scorpion.pojo;

public class PolicyOfZmq extends PolicyOfZmqKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zimaoqu_policy.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zimaoqu_policy.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zimaoqu_policy.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zimaoqu_policy.category
     *
     * @return the value of zimaoqu_policy.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zimaoqu_policy.category
     *
     * @param category the value for zimaoqu_policy.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zimaoqu_policy.source
     *
     * @return the value of zimaoqu_policy.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zimaoqu_policy.source
     *
     * @param source the value for zimaoqu_policy.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zimaoqu_policy.count
     *
     * @return the value of zimaoqu_policy.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zimaoqu_policy.count
     *
     * @param count the value for zimaoqu_policy.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}