package com.scorpion.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TopCompanyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table top_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table top_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table top_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public TopCompanyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table top_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNbxhIsNull() {
            addCriterion("nbxh is null");
            return (Criteria) this;
        }

        public Criteria andNbxhIsNotNull() {
            addCriterion("nbxh is not null");
            return (Criteria) this;
        }

        public Criteria andNbxhEqualTo(String value) {
            addCriterion("nbxh =", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhNotEqualTo(String value) {
            addCriterion("nbxh <>", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhGreaterThan(String value) {
            addCriterion("nbxh >", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhGreaterThanOrEqualTo(String value) {
            addCriterion("nbxh >=", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhLessThan(String value) {
            addCriterion("nbxh <", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhLessThanOrEqualTo(String value) {
            addCriterion("nbxh <=", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhLike(String value) {
            addCriterion("nbxh like", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhNotLike(String value) {
            addCriterion("nbxh not like", value, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhIn(List<String> values) {
            addCriterion("nbxh in", values, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhNotIn(List<String> values) {
            addCriterion("nbxh not in", values, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhBetween(String value1, String value2) {
            addCriterion("nbxh between", value1, value2, "nbxh");
            return (Criteria) this;
        }

        public Criteria andNbxhNotBetween(String value1, String value2) {
            addCriterion("nbxh not between", value1, value2, "nbxh");
            return (Criteria) this;
        }

        public Criteria andQymcIsNull() {
            addCriterion("qymc is null");
            return (Criteria) this;
        }

        public Criteria andQymcIsNotNull() {
            addCriterion("qymc is not null");
            return (Criteria) this;
        }

        public Criteria andQymcEqualTo(String value) {
            addCriterion("qymc =", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotEqualTo(String value) {
            addCriterion("qymc <>", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcGreaterThan(String value) {
            addCriterion("qymc >", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcGreaterThanOrEqualTo(String value) {
            addCriterion("qymc >=", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLessThan(String value) {
            addCriterion("qymc <", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLessThanOrEqualTo(String value) {
            addCriterion("qymc <=", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLike(String value) {
            addCriterion("qymc like", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotLike(String value) {
            addCriterion("qymc not like", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcIn(List<String> values) {
            addCriterion("qymc in", values, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotIn(List<String> values) {
            addCriterion("qymc not in", values, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcBetween(String value1, String value2) {
            addCriterion("qymc between", value1, value2, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotBetween(String value1, String value2) {
            addCriterion("qymc not between", value1, value2, "qymc");
            return (Criteria) this;
        }

        public Criteria andQyzchIsNull() {
            addCriterion("qyzch is null");
            return (Criteria) this;
        }

        public Criteria andQyzchIsNotNull() {
            addCriterion("qyzch is not null");
            return (Criteria) this;
        }

        public Criteria andQyzchEqualTo(String value) {
            addCriterion("qyzch =", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchNotEqualTo(String value) {
            addCriterion("qyzch <>", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchGreaterThan(String value) {
            addCriterion("qyzch >", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchGreaterThanOrEqualTo(String value) {
            addCriterion("qyzch >=", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchLessThan(String value) {
            addCriterion("qyzch <", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchLessThanOrEqualTo(String value) {
            addCriterion("qyzch <=", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchLike(String value) {
            addCriterion("qyzch like", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchNotLike(String value) {
            addCriterion("qyzch not like", value, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchIn(List<String> values) {
            addCriterion("qyzch in", values, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchNotIn(List<String> values) {
            addCriterion("qyzch not in", values, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchBetween(String value1, String value2) {
            addCriterion("qyzch between", value1, value2, "qyzch");
            return (Criteria) this;
        }

        public Criteria andQyzchNotBetween(String value1, String value2) {
            addCriterion("qyzch not between", value1, value2, "qyzch");
            return (Criteria) this;
        }

        public Criteria andFddbrIsNull() {
            addCriterion("fddbr is null");
            return (Criteria) this;
        }

        public Criteria andFddbrIsNotNull() {
            addCriterion("fddbr is not null");
            return (Criteria) this;
        }

        public Criteria andFddbrEqualTo(String value) {
            addCriterion("fddbr =", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrNotEqualTo(String value) {
            addCriterion("fddbr <>", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrGreaterThan(String value) {
            addCriterion("fddbr >", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrGreaterThanOrEqualTo(String value) {
            addCriterion("fddbr >=", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrLessThan(String value) {
            addCriterion("fddbr <", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrLessThanOrEqualTo(String value) {
            addCriterion("fddbr <=", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrLike(String value) {
            addCriterion("fddbr like", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrNotLike(String value) {
            addCriterion("fddbr not like", value, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrIn(List<String> values) {
            addCriterion("fddbr in", values, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrNotIn(List<String> values) {
            addCriterion("fddbr not in", values, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrBetween(String value1, String value2) {
            addCriterion("fddbr between", value1, value2, "fddbr");
            return (Criteria) this;
        }

        public Criteria andFddbrNotBetween(String value1, String value2) {
            addCriterion("fddbr not between", value1, value2, "fddbr");
            return (Criteria) this;
        }

        public Criteria andQylxIsNull() {
            addCriterion("qylx is null");
            return (Criteria) this;
        }

        public Criteria andQylxIsNotNull() {
            addCriterion("qylx is not null");
            return (Criteria) this;
        }

        public Criteria andQylxEqualTo(String value) {
            addCriterion("qylx =", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxNotEqualTo(String value) {
            addCriterion("qylx <>", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxGreaterThan(String value) {
            addCriterion("qylx >", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxGreaterThanOrEqualTo(String value) {
            addCriterion("qylx >=", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxLessThan(String value) {
            addCriterion("qylx <", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxLessThanOrEqualTo(String value) {
            addCriterion("qylx <=", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxLike(String value) {
            addCriterion("qylx like", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxNotLike(String value) {
            addCriterion("qylx not like", value, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxIn(List<String> values) {
            addCriterion("qylx in", values, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxNotIn(List<String> values) {
            addCriterion("qylx not in", values, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxBetween(String value1, String value2) {
            addCriterion("qylx between", value1, value2, "qylx");
            return (Criteria) this;
        }

        public Criteria andQylxNotBetween(String value1, String value2) {
            addCriterion("qylx not between", value1, value2, "qylx");
            return (Criteria) this;
        }

        public Criteria andZtIsNull() {
            addCriterion("zt is null");
            return (Criteria) this;
        }

        public Criteria andZtIsNotNull() {
            addCriterion("zt is not null");
            return (Criteria) this;
        }

        public Criteria andZtEqualTo(String value) {
            addCriterion("zt =", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotEqualTo(String value) {
            addCriterion("zt <>", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThan(String value) {
            addCriterion("zt >", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtGreaterThanOrEqualTo(String value) {
            addCriterion("zt >=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThan(String value) {
            addCriterion("zt <", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLessThanOrEqualTo(String value) {
            addCriterion("zt <=", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtLike(String value) {
            addCriterion("zt like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotLike(String value) {
            addCriterion("zt not like", value, "zt");
            return (Criteria) this;
        }

        public Criteria andZtIn(List<String> values) {
            addCriterion("zt in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotIn(List<String> values) {
            addCriterion("zt not in", values, "zt");
            return (Criteria) this;
        }

        public Criteria andZtBetween(String value1, String value2) {
            addCriterion("zt between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andZtNotBetween(String value1, String value2) {
            addCriterion("zt not between", value1, value2, "zt");
            return (Criteria) this;
        }

        public Criteria andZczbIsNull() {
            addCriterion("zczb is null");
            return (Criteria) this;
        }

        public Criteria andZczbIsNotNull() {
            addCriterion("zczb is not null");
            return (Criteria) this;
        }

        public Criteria andZczbEqualTo(String value) {
            addCriterion("zczb =", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbNotEqualTo(String value) {
            addCriterion("zczb <>", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbGreaterThan(String value) {
            addCriterion("zczb >", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbGreaterThanOrEqualTo(String value) {
            addCriterion("zczb >=", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbLessThan(String value) {
            addCriterion("zczb <", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbLessThanOrEqualTo(String value) {
            addCriterion("zczb <=", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbLike(String value) {
            addCriterion("zczb like", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbNotLike(String value) {
            addCriterion("zczb not like", value, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbIn(List<String> values) {
            addCriterion("zczb in", values, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbNotIn(List<String> values) {
            addCriterion("zczb not in", values, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbBetween(String value1, String value2) {
            addCriterion("zczb between", value1, value2, "zczb");
            return (Criteria) this;
        }

        public Criteria andZczbNotBetween(String value1, String value2) {
            addCriterion("zczb not between", value1, value2, "zczb");
            return (Criteria) this;
        }

        public Criteria andZsIsNull() {
            addCriterion("zs is null");
            return (Criteria) this;
        }

        public Criteria andZsIsNotNull() {
            addCriterion("zs is not null");
            return (Criteria) this;
        }

        public Criteria andZsEqualTo(String value) {
            addCriterion("zs =", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsNotEqualTo(String value) {
            addCriterion("zs <>", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsGreaterThan(String value) {
            addCriterion("zs >", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsGreaterThanOrEqualTo(String value) {
            addCriterion("zs >=", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsLessThan(String value) {
            addCriterion("zs <", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsLessThanOrEqualTo(String value) {
            addCriterion("zs <=", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsLike(String value) {
            addCriterion("zs like", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsNotLike(String value) {
            addCriterion("zs not like", value, "zs");
            return (Criteria) this;
        }

        public Criteria andZsIn(List<String> values) {
            addCriterion("zs in", values, "zs");
            return (Criteria) this;
        }

        public Criteria andZsNotIn(List<String> values) {
            addCriterion("zs not in", values, "zs");
            return (Criteria) this;
        }

        public Criteria andZsBetween(String value1, String value2) {
            addCriterion("zs between", value1, value2, "zs");
            return (Criteria) this;
        }

        public Criteria andZsNotBetween(String value1, String value2) {
            addCriterion("zs not between", value1, value2, "zs");
            return (Criteria) this;
        }

        public Criteria andJyfwIsNull() {
            addCriterion("jyfw is null");
            return (Criteria) this;
        }

        public Criteria andJyfwIsNotNull() {
            addCriterion("jyfw is not null");
            return (Criteria) this;
        }

        public Criteria andJyfwEqualTo(String value) {
            addCriterion("jyfw =", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwNotEqualTo(String value) {
            addCriterion("jyfw <>", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwGreaterThan(String value) {
            addCriterion("jyfw >", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwGreaterThanOrEqualTo(String value) {
            addCriterion("jyfw >=", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwLessThan(String value) {
            addCriterion("jyfw <", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwLessThanOrEqualTo(String value) {
            addCriterion("jyfw <=", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwLike(String value) {
            addCriterion("jyfw like", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwNotLike(String value) {
            addCriterion("jyfw not like", value, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwIn(List<String> values) {
            addCriterion("jyfw in", values, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwNotIn(List<String> values) {
            addCriterion("jyfw not in", values, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwBetween(String value1, String value2) {
            addCriterion("jyfw between", value1, value2, "jyfw");
            return (Criteria) this;
        }

        public Criteria andJyfwNotBetween(String value1, String value2) {
            addCriterion("jyfw not between", value1, value2, "jyfw");
            return (Criteria) this;
        }

        public Criteria andGxdwIsNull() {
            addCriterion("gxdw is null");
            return (Criteria) this;
        }

        public Criteria andGxdwIsNotNull() {
            addCriterion("gxdw is not null");
            return (Criteria) this;
        }

        public Criteria andGxdwEqualTo(String value) {
            addCriterion("gxdw =", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwNotEqualTo(String value) {
            addCriterion("gxdw <>", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwGreaterThan(String value) {
            addCriterion("gxdw >", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwGreaterThanOrEqualTo(String value) {
            addCriterion("gxdw >=", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwLessThan(String value) {
            addCriterion("gxdw <", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwLessThanOrEqualTo(String value) {
            addCriterion("gxdw <=", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwLike(String value) {
            addCriterion("gxdw like", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwNotLike(String value) {
            addCriterion("gxdw not like", value, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwIn(List<String> values) {
            addCriterion("gxdw in", values, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwNotIn(List<String> values) {
            addCriterion("gxdw not in", values, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwBetween(String value1, String value2) {
            addCriterion("gxdw between", value1, value2, "gxdw");
            return (Criteria) this;
        }

        public Criteria andGxdwNotBetween(String value1, String value2) {
            addCriterion("gxdw not between", value1, value2, "gxdw");
            return (Criteria) this;
        }

        public Criteria andXkksrqIsNull() {
            addCriterion("xkksrq is null");
            return (Criteria) this;
        }

        public Criteria andXkksrqIsNotNull() {
            addCriterion("xkksrq is not null");
            return (Criteria) this;
        }

        public Criteria andXkksrqEqualTo(String value) {
            addCriterion("xkksrq =", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqNotEqualTo(String value) {
            addCriterion("xkksrq <>", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqGreaterThan(String value) {
            addCriterion("xkksrq >", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqGreaterThanOrEqualTo(String value) {
            addCriterion("xkksrq >=", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqLessThan(String value) {
            addCriterion("xkksrq <", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqLessThanOrEqualTo(String value) {
            addCriterion("xkksrq <=", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqLike(String value) {
            addCriterion("xkksrq like", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqNotLike(String value) {
            addCriterion("xkksrq not like", value, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqIn(List<String> values) {
            addCriterion("xkksrq in", values, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqNotIn(List<String> values) {
            addCriterion("xkksrq not in", values, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqBetween(String value1, String value2) {
            addCriterion("xkksrq between", value1, value2, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkksrqNotBetween(String value1, String value2) {
            addCriterion("xkksrq not between", value1, value2, "xkksrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqIsNull() {
            addCriterion("xkjsrq is null");
            return (Criteria) this;
        }

        public Criteria andXkjsrqIsNotNull() {
            addCriterion("xkjsrq is not null");
            return (Criteria) this;
        }

        public Criteria andXkjsrqEqualTo(String value) {
            addCriterion("xkjsrq =", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqNotEqualTo(String value) {
            addCriterion("xkjsrq <>", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqGreaterThan(String value) {
            addCriterion("xkjsrq >", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqGreaterThanOrEqualTo(String value) {
            addCriterion("xkjsrq >=", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqLessThan(String value) {
            addCriterion("xkjsrq <", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqLessThanOrEqualTo(String value) {
            addCriterion("xkjsrq <=", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqLike(String value) {
            addCriterion("xkjsrq like", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqNotLike(String value) {
            addCriterion("xkjsrq not like", value, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqIn(List<String> values) {
            addCriterion("xkjsrq in", values, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqNotIn(List<String> values) {
            addCriterion("xkjsrq not in", values, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqBetween(String value1, String value2) {
            addCriterion("xkjsrq between", value1, value2, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andXkjsrqNotBetween(String value1, String value2) {
            addCriterion("xkjsrq not between", value1, value2, "xkjsrq");
            return (Criteria) this;
        }

        public Criteria andSlrqIsNull() {
            addCriterion("slrq is null");
            return (Criteria) this;
        }

        public Criteria andSlrqIsNotNull() {
            addCriterion("slrq is not null");
            return (Criteria) this;
        }

        public Criteria andSlrqEqualTo(String value) {
            addCriterion("slrq =", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqNotEqualTo(String value) {
            addCriterion("slrq <>", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqGreaterThan(String value) {
            addCriterion("slrq >", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqGreaterThanOrEqualTo(String value) {
            addCriterion("slrq >=", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqLessThan(String value) {
            addCriterion("slrq <", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqLessThanOrEqualTo(String value) {
            addCriterion("slrq <=", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqLike(String value) {
            addCriterion("slrq like", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqNotLike(String value) {
            addCriterion("slrq not like", value, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqIn(List<String> values) {
            addCriterion("slrq in", values, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqNotIn(List<String> values) {
            addCriterion("slrq not in", values, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqBetween(String value1, String value2) {
            addCriterion("slrq between", value1, value2, "slrq");
            return (Criteria) this;
        }

        public Criteria andSlrqNotBetween(String value1, String value2) {
            addCriterion("slrq not between", value1, value2, "slrq");
            return (Criteria) this;
        }

        public Criteria andHyIsNull() {
            addCriterion("hy is null");
            return (Criteria) this;
        }

        public Criteria andHyIsNotNull() {
            addCriterion("hy is not null");
            return (Criteria) this;
        }

        public Criteria andHyEqualTo(String value) {
            addCriterion("hy =", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyNotEqualTo(String value) {
            addCriterion("hy <>", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyGreaterThan(String value) {
            addCriterion("hy >", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyGreaterThanOrEqualTo(String value) {
            addCriterion("hy >=", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyLessThan(String value) {
            addCriterion("hy <", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyLessThanOrEqualTo(String value) {
            addCriterion("hy <=", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyLike(String value) {
            addCriterion("hy like", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyNotLike(String value) {
            addCriterion("hy not like", value, "hy");
            return (Criteria) this;
        }

        public Criteria andHyIn(List<String> values) {
            addCriterion("hy in", values, "hy");
            return (Criteria) this;
        }

        public Criteria andHyNotIn(List<String> values) {
            addCriterion("hy not in", values, "hy");
            return (Criteria) this;
        }

        public Criteria andHyBetween(String value1, String value2) {
            addCriterion("hy between", value1, value2, "hy");
            return (Criteria) this;
        }

        public Criteria andHyNotBetween(String value1, String value2) {
            addCriterion("hy not between", value1, value2, "hy");
            return (Criteria) this;
        }

        public Criteria andZzjgdmIsNull() {
            addCriterion("zzjgdm is null");
            return (Criteria) this;
        }

        public Criteria andZzjgdmIsNotNull() {
            addCriterion("zzjgdm is not null");
            return (Criteria) this;
        }

        public Criteria andZzjgdmEqualTo(String value) {
            addCriterion("zzjgdm =", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmNotEqualTo(String value) {
            addCriterion("zzjgdm <>", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmGreaterThan(String value) {
            addCriterion("zzjgdm >", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmGreaterThanOrEqualTo(String value) {
            addCriterion("zzjgdm >=", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmLessThan(String value) {
            addCriterion("zzjgdm <", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmLessThanOrEqualTo(String value) {
            addCriterion("zzjgdm <=", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmLike(String value) {
            addCriterion("zzjgdm like", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmNotLike(String value) {
            addCriterion("zzjgdm not like", value, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmIn(List<String> values) {
            addCriterion("zzjgdm in", values, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmNotIn(List<String> values) {
            addCriterion("zzjgdm not in", values, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmBetween(String value1, String value2) {
            addCriterion("zzjgdm between", value1, value2, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andZzjgdmNotBetween(String value1, String value2) {
            addCriterion("zzjgdm not between", value1, value2, "zzjgdm");
            return (Criteria) this;
        }

        public Criteria andHzrqIsNull() {
            addCriterion("hzrq is null");
            return (Criteria) this;
        }

        public Criteria andHzrqIsNotNull() {
            addCriterion("hzrq is not null");
            return (Criteria) this;
        }

        public Criteria andHzrqEqualTo(String value) {
            addCriterion("hzrq =", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqNotEqualTo(String value) {
            addCriterion("hzrq <>", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqGreaterThan(String value) {
            addCriterion("hzrq >", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqGreaterThanOrEqualTo(String value) {
            addCriterion("hzrq >=", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqLessThan(String value) {
            addCriterion("hzrq <", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqLessThanOrEqualTo(String value) {
            addCriterion("hzrq <=", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqLike(String value) {
            addCriterion("hzrq like", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqNotLike(String value) {
            addCriterion("hzrq not like", value, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqIn(List<String> values) {
            addCriterion("hzrq in", values, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqNotIn(List<String> values) {
            addCriterion("hzrq not in", values, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqBetween(String value1, String value2) {
            addCriterion("hzrq between", value1, value2, "hzrq");
            return (Criteria) this;
        }

        public Criteria andHzrqNotBetween(String value1, String value2) {
            addCriterion("hzrq not between", value1, value2, "hzrq");
            return (Criteria) this;
        }

        public Criteria andTyshxydmIsNull() {
            addCriterion("tyshxydm is null");
            return (Criteria) this;
        }

        public Criteria andTyshxydmIsNotNull() {
            addCriterion("tyshxydm is not null");
            return (Criteria) this;
        }

        public Criteria andTyshxydmEqualTo(String value) {
            addCriterion("tyshxydm =", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmNotEqualTo(String value) {
            addCriterion("tyshxydm <>", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmGreaterThan(String value) {
            addCriterion("tyshxydm >", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmGreaterThanOrEqualTo(String value) {
            addCriterion("tyshxydm >=", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmLessThan(String value) {
            addCriterion("tyshxydm <", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmLessThanOrEqualTo(String value) {
            addCriterion("tyshxydm <=", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmLike(String value) {
            addCriterion("tyshxydm like", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmNotLike(String value) {
            addCriterion("tyshxydm not like", value, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmIn(List<String> values) {
            addCriterion("tyshxydm in", values, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmNotIn(List<String> values) {
            addCriterion("tyshxydm not in", values, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmBetween(String value1, String value2) {
            addCriterion("tyshxydm between", value1, value2, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andTyshxydmNotBetween(String value1, String value2) {
            addCriterion("tyshxydm not between", value1, value2, "tyshxydm");
            return (Criteria) this;
        }

        public Criteria andCymIsNull() {
            addCriterion("cym is null");
            return (Criteria) this;
        }

        public Criteria andCymIsNotNull() {
            addCriterion("cym is not null");
            return (Criteria) this;
        }

        public Criteria andCymEqualTo(String value) {
            addCriterion("cym =", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymNotEqualTo(String value) {
            addCriterion("cym <>", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymGreaterThan(String value) {
            addCriterion("cym >", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymGreaterThanOrEqualTo(String value) {
            addCriterion("cym >=", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymLessThan(String value) {
            addCriterion("cym <", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymLessThanOrEqualTo(String value) {
            addCriterion("cym <=", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymLike(String value) {
            addCriterion("cym like", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymNotLike(String value) {
            addCriterion("cym not like", value, "cym");
            return (Criteria) this;
        }

        public Criteria andCymIn(List<String> values) {
            addCriterion("cym in", values, "cym");
            return (Criteria) this;
        }

        public Criteria andCymNotIn(List<String> values) {
            addCriterion("cym not in", values, "cym");
            return (Criteria) this;
        }

        public Criteria andCymBetween(String value1, String value2) {
            addCriterion("cym between", value1, value2, "cym");
            return (Criteria) this;
        }

        public Criteria andCymNotBetween(String value1, String value2) {
            addCriterion("cym not between", value1, value2, "cym");
            return (Criteria) this;
        }

        public Criteria andRksjIsNull() {
            addCriterion("rksj is null");
            return (Criteria) this;
        }

        public Criteria andRksjIsNotNull() {
            addCriterion("rksj is not null");
            return (Criteria) this;
        }

        public Criteria andRksjEqualTo(Date value) {
            addCriterion("rksj =", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotEqualTo(Date value) {
            addCriterion("rksj <>", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThan(Date value) {
            addCriterion("rksj >", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjGreaterThanOrEqualTo(Date value) {
            addCriterion("rksj >=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThan(Date value) {
            addCriterion("rksj <", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjLessThanOrEqualTo(Date value) {
            addCriterion("rksj <=", value, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjIn(List<Date> values) {
            addCriterion("rksj in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotIn(List<Date> values) {
            addCriterion("rksj not in", values, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjBetween(Date value1, Date value2) {
            addCriterion("rksj between", value1, value2, "rksj");
            return (Criteria) this;
        }

        public Criteria andRksjNotBetween(Date value1, Date value2) {
            addCriterion("rksj not between", value1, value2, "rksj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table top_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table top_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}