package com.scorpion.pojo;

public class TopKeyAttentionWithBLOBs extends TopKeyAttention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.name
     *
     * @mbggenerated
     */
    private Integer id;
    private String word;
    private String date;
    private String name;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.html
     *
     * @mbggenerated
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.Relcompany
     *
     * @mbggenerated
     */
    private String relcompany;



    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.word
     *
     * @param word the value for toptest.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.name
     *
     * @return the value of toptest.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.name
     *
     * @param name the value for toptest.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.title
     *
     * @return the value of toptest.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.title
     *
     * @param title the value for toptest.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.url
     *
     * @return the value of toptest.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.url
     *
     * @param url the value for toptest.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.description
     *
     * @return the value of toptest.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.description
     *
     * @param description the value for toptest.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.html
     *
     * @return the value of toptest.html
     *
     * @mbggenerated
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.html
     *
     * @param html the value for toptest.html
     *
     * @mbggenerated
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.keywords
     *
     * @return the value of toptest.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.keywords
     *
     * @param keywords the value for toptest.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.Relcompany
     *
     * @return the value of toptest.Relcompany
     *
     * @mbggenerated
     */
    public String getRelcompany() {
        return relcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.Relcompany
     *
     * @param relcompany the value for toptest.Relcompany
     *
     * @mbggenerated
     */
    public void setRelcompany(String relcompany) {
        this.relcompany = relcompany == null ? null : relcompany.trim();
    }
}