package com.scorpion.pojo;

import java.util.Date;

public class TopKeyAttention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.id
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.date
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.oreitation
     *
     * @mbggenerated
     */
    private Integer oreitation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.oreitationvalue
     *
     * @mbggenerated
     */
    private Float oreitationvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toptest.word
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.flag
     *
     * @return the value of toptest.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.flag
     *
     * @param flag the value for toptest.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.id
     *
     * @return the value of toptest.id
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.id
     *
     * @param id the value for toptest.id
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.date
     *
     * @return the value of toptest.date
     *

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.date
     *
     * @param date the value for toptest.date
     *
     * @mbggenerated

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.category
     *
     * @return the value of toptest.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.category
     *
     * @param category the value for toptest.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.source
     *
     * @return the value of toptest.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.source
     *
     * @param source the value for toptest.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.count
     *
     * @return the value of toptest.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.count
     *
     * @param count the value for toptest.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.oreitation
     *
     * @return the value of toptest.oreitation
     *
     * @mbggenerated
     */
    public Integer getOreitation() {
        return oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.oreitation
     *
     * @param oreitation the value for toptest.oreitation
     *
     * @mbggenerated
     */
    public void setOreitation(Integer oreitation) {
        this.oreitation = oreitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.topic
     *
     * @return the value of toptest.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.topic
     *
     * @param topic the value for toptest.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.oreitationvalue
     *
     * @return the value of toptest.oreitationvalue
     *
     * @mbggenerated
     */
    public Float getOreitationvalue() {
        return oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toptest.oreitationvalue
     *
     * @param oreitationvalue the value for toptest.oreitationvalue
     *
     * @mbggenerated
     */
    public void setOreitationvalue(Float oreitationvalue) {
        this.oreitationvalue = oreitationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toptest.word
     *
     * @return the value of toptest.word
     *
     * @mbggenerated
     */
}