package com.scorpion.pojo;

public class ZmqEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_event.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_event.zname
     *
     * @mbggenerated
     */
    private String zname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_event.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_event.event
     *
     * @mbggenerated
     */
    private String event;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_event.id
     *
     * @return the value of zmq_event.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_event.id
     *
     * @param id the value for zmq_event.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_event.zname
     *
     * @return the value of zmq_event.zname
     *
     * @mbggenerated
     */
    public String getZname() {
        return zname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_event.zname
     *
     * @param zname the value for zmq_event.zname
     *
     * @mbggenerated
     */
    public void setZname(String zname) {
        this.zname = zname == null ? null : zname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_event.date
     *
     * @return the value of zmq_event.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_event.date
     *
     * @param date the value for zmq_event.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_event.event
     *
     * @return the value of zmq_event.event
     *
     * @mbggenerated
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_event.event
     *
     * @param event the value for zmq_event.event
     *
     * @mbggenerated
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }
}