package com.scorpion.pojo;

import java.util.Date;

public class ZmqIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_index.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_index.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_index.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zmq_index.index
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_index.keyword
     *
     * @return the value of zmq_index.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_index.keyword
     *
     * @param keyword the value for zmq_index.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_index.date
     *
     * @return the value of zmq_index.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_index.date
     *
     * @param date the value for zmq_index.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_index.type
     *
     * @return the value of zmq_index.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_index.type
     *
     * @param type the value for zmq_index.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zmq_index.index
     *
     * @return the value of zmq_index.index
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zmq_index.index
     *
     * @param index the value for zmq_index.index
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}