package com.scorpion.dao;

import com.scorpion.pojo.adminInfo;
import com.scorpion.pojo.adminInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface adminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int countByExample(adminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int deleteByExample(adminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int insert(adminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int insertSelective(adminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    List<adminInfo> selectByExample(adminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") adminInfo record, @Param("example") adminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") adminInfo record, @Param("example") adminInfoExample example);

    public adminInfo findUserByName(String username);
}