package com.scorpion.dao;

import com.scorpion.pojo.bignews;
import com.scorpion.pojo.bignewsExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface bignewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int countByExample(bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int deleteByExample(bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int insert(bignews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int insertSelective(bignews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    List<bignews> selectByExampleWithBLOBs(bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    List<bignews> selectByExample(bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    bignews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") bignews record, @Param("example") bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") bignews record, @Param("example") bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") bignews record, @Param("example") bignewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(bignews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(bignews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bignews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(bignews record);

    List<String> getComList();

    List<bignews> getHisEvents(Map map);
}