package com.scorpion.dao;

import com.scorpion.pojo.ComHealthValue;
import com.scorpion.pojo.ComHealthValueExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ComHealthValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int countByExample(ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int deleteByExample(ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int insert(ComHealthValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int insertSelective(ComHealthValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    List<ComHealthValue> selectByExampleWithBLOBs(ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    List<ComHealthValue> selectByExample(ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    ComHealthValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ComHealthValue record, @Param("example") ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ComHealthValue record, @Param("example") ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ComHealthValue record, @Param("example") ComHealthValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComHealthValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ComHealthValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comhealth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComHealthValue record);

    String getNegNumStringMonth(Map map);

    String getNegNumStringSeason(Map map);

    String getPosNumStringMonth(Map map);

    String getPosNumStringSeason(Map map);

    String getHealthValueStringMonth(Map map);

    String getHealthValueStringSeason(Map map);

    double getHealthValue(Map map);

}