package com.scorpion.dao;

import com.scorpion.pojo.companyinformation;
import com.scorpion.pojo.companyinformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface companyinformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int countByExample(companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int deleteByExample(companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int insert(companyinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int insertSelective(companyinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    List<companyinformation> selectByExampleWithBLOBs(companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    List<companyinformation> selectByExample(companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    companyinformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") companyinformation record, @Param("example") companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") companyinformation record, @Param("example") companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") companyinformation record, @Param("example") companyinformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(companyinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(companyinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companyinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(companyinformation record);

    List<companyinformation> queryComInfo();
}