package com.scorpion.dao;

import com.scorpion.pojo.crude_btl;
import com.scorpion.pojo.crude_btlExample;
import com.scorpion.pojo.crude_btlKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface crude_btlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int countByExample(crude_btlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int deleteByExample(crude_btlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(crude_btlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int insert(crude_btl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int insertSelective(crude_btl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    List<crude_btl> selectByExample(crude_btlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    crude_btl selectByPrimaryKey(crude_btlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") crude_btl record, @Param("example") crude_btlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") crude_btl record, @Param("example") crude_btlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(crude_btl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_btl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(crude_btl record);
    /**
     * 获取全国crude_btl的数据
     * @return
     */
    List<crude_btl> selectAllCrude_btl();
}