package com.scorpion.dao;

import com.scorpion.pojo.crude_wti;
import com.scorpion.pojo.crude_wtiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface crude_wtiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int countByExample(crude_wtiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int deleteByExample(crude_wtiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int insert(crude_wti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int insertSelective(crude_wti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    List<crude_wti> selectByExample(crude_wtiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    crude_wti selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") crude_wti record, @Param("example") crude_wtiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") crude_wti record, @Param("example") crude_wtiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(crude_wti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crude_wti
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(crude_wti record);
    /**
     * 获取Crude_wti数据
     * @return
     */
    List<crude_wti> selectAllCrude_wti();
}