package com.scorpion.dao;

import com.scorpion.pojo.SourceOfNews;
import com.scorpion.pojo.currentnews;
import com.scorpion.pojo.currentnewsExample;
import com.scorpion.pojo.currentnewsWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface currentnewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int countByExample(currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int deleteByExample(currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int insert(currentnewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int insertSelective(currentnewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    List<currentnewsWithBLOBs> selectByExampleWithBLOBs(currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    List<currentnews> selectByExample(currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    currentnewsWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") currentnewsWithBLOBs record, @Param("example") currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") currentnewsWithBLOBs record, @Param("example") currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") currentnews record, @Param("example") currentnewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(currentnewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(currentnewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currentnews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(currentnews record);

    /**
     * query currentnews
     * @return
     */
    List<currentnewsWithBLOBs> queryCurrentnews();

    /**
     * 获取热词
     * @return
     */
    List<String> getKeywords(Map map);

    /**
     * 新闻来源统计
     * @param map
     * @return
     */
    List<SourceOfNews> getCountSource(Map map);

    /**
     * 获取热点新闻
     * @param map
     * @return
     */
    List<currentnewsWithBLOBs> getHotNews(Map map);

    /**
     * 获取敏感新闻
     * @param map
     * @return
     */
    List<currentnewsWithBLOBs> getSensiveNews(Map map);

}