package com.scorpion.dao;

import com.scorpion.pojo.imf;
import com.scorpion.pojo.imfExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface imfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int countByExample(imfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int deleteByExample(imfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int insert(imf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int insertSelective(imf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    List<imf> selectByExample(imfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    imf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") imf record, @Param("example") imfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") imf record, @Param("example") imfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(imf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(imf record);
    /**
     * 获取全imf的数据
     * @return
     */
    List<imf> selectAllimf();
}