package com.scorpion.dao;

import com.scorpion.pojo.IndicateOfExportImport;
import com.scorpion.pojo.IndicateOfExportImportExample;
import java.util.List;

import com.scorpion.pojo.IndicateOfPPI;
import org.apache.ibatis.annotations.Param;

public interface IndicateOfExportImportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int countByExample(IndicateOfExportImportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int deleteByExample(IndicateOfExportImportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int insert(IndicateOfExportImport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int insertSelective(IndicateOfExportImport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    List<IndicateOfExportImport> selectByExample(IndicateOfExportImportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    IndicateOfExportImport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IndicateOfExportImport record, @Param("example") IndicateOfExportImportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IndicateOfExportImport record, @Param("example") IndicateOfExportImportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndicateOfExportImport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_import
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndicateOfExportImport record);

    /**
     * 获取全国进出口总额的数据
     * @return
     */
    List<IndicateOfExportImport> selectAllExportImport();
}