package com.scorpion.dao;


import com.scorpion.pojo.IndicateOfGDPSH;
import com.scorpion.pojo.IndicateOfGDPSHExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndicateOfGDPSHMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int countByExample(IndicateOfGDPSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int deleteByExample(IndicateOfGDPSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int insert(IndicateOfGDPSH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int insertSelective(IndicateOfGDPSH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    List<IndicateOfGDPSH> selectByExample(IndicateOfGDPSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    IndicateOfGDPSH selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IndicateOfGDPSH record, @Param("example") IndicateOfGDPSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IndicateOfGDPSH record, @Param("example") IndicateOfGDPSHExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndicateOfGDPSH record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ppi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndicateOfGDPSH record);

    /**
     * 获取上海所有GDP的数据
     * @return
     */
    List<IndicateOfGDPSH> selectAllGDPSH();
}