package com.scorpion.dao;

import com.scorpion.pojo.IndicateOfGDPCountry;
import com.scorpion.pojo.IndicateOfGDPCountryExample;
import java.util.List;
import java.util.Map;

import com.scorpion.pojo.IndicateOfGDPSH;
import com.scorpion.pojo.NewsOfCompanyWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface IndicateOfGDPCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int countByExample(IndicateOfGDPCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int deleteByExample(IndicateOfGDPCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int insert(IndicateOfGDPCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int insertSelective(IndicateOfGDPCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    List<IndicateOfGDPCountry> selectByExample(IndicateOfGDPCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    IndicateOfGDPCountry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IndicateOfGDPCountry record, @Param("example") IndicateOfGDPCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IndicateOfGDPCountry record, @Param("example") IndicateOfGDPCountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndicateOfGDPCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdp_country
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndicateOfGDPCountry record);

    /**
     * 获取全国所有GDP的数据
     * @return
     */
    List<IndicateOfGDPCountry> selectAllGDPCountry();
}