package com.scorpion.dao;

import com.scorpion.pojo.IndicateOfCPI;
import com.scorpion.pojo.IndicateOfCPIExample;
import java.util.List;

import com.scorpion.pojo.IndicateOfPPI;
import org.apache.ibatis.annotations.Param;

public interface IndicateOfCPIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int countByExample(IndicateOfCPIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int deleteByExample(IndicateOfCPIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int insert(IndicateOfCPI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int insertSelective(IndicateOfCPI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    List<IndicateOfCPI> selectByExample(IndicateOfCPIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    IndicateOfCPI selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IndicateOfCPI record, @Param("example") IndicateOfCPIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IndicateOfCPI record, @Param("example") IndicateOfCPIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IndicateOfCPI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cpi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IndicateOfCPI record);

    /**
     * 获取全国PPI的数据
     * @return
     */
    List<IndicateOfCPI> selectAllCPI();
}