package com.scorpion.dao;

import com.scorpion.pojo.MediaIndex;
import com.scorpion.pojo.MediaIndexExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MediaIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int countByExample(MediaIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int deleteByExample(MediaIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int insert(MediaIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int insertSelective(MediaIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    List<MediaIndex> selectByExample(MediaIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MediaIndex record, @Param("example") MediaIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediaindex
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MediaIndex record, @Param("example") MediaIndexExample example);

    List<Integer> getMediaIndexList(Map map);
}