package com.scorpion.dao;

import com.scorpion.pojo.*;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NewsOfTopCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int countByExample(NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int deleteByExample(NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int insert(NewsOfTopCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int insertSelective(NewsOfTopCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    List<NewsOfTopCompanyWithBLOBs> selectByExampleWithBLOBs(NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    List<NewsOfTopCompany> selectByExample(NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    NewsOfTopCompanyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NewsOfTopCompanyWithBLOBs record, @Param("example") NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") NewsOfTopCompanyWithBLOBs record, @Param("example") NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NewsOfTopCompany record, @Param("example") NewsOfTopCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsOfTopCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsOfTopCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topcompany
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsOfTopCompany record);
    /**
     * 获取所有公司的新闻
     * @return
     */

    List<NewsOfTopCompanyWithBLOBs> selectAllNews(Map map);

    /**
     * 获取匹配结果的公司的新闻
     * @return
     */

    List<NewsOfTopCompanyWithBLOBs> selectMatchNews(Map map);

    /**
     * 获取匹配结果的公司的新闻数
     * @return
     */

    List<ComNameNewsCount> getTopMatchNewsCount(Map map);
    /**
     * 获取所有新闻的条数
     */
    int countAllNews();
    /**
     * 获取匹配新闻的条数
     */
    int countMatchNews(Map map);
    /*
    企业新闻数统计
     */
    List<ComNameNewsCount> TopNewsCount();
}