package com.scorpion.dao;

import com.scorpion.pojo.NewsOfCompany;
import com.scorpion.pojo.NewsOfCompanyExample;
import com.scorpion.pojo.NewsOfCompanyWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NewsOfCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int countByExample(NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int deleteByExample(NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int insert(NewsOfCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int insertSelective(NewsOfCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    List<NewsOfCompanyWithBLOBs> selectByExampleWithBLOBs(NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    List<NewsOfCompany> selectByExample(NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    NewsOfCompanyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NewsOfCompanyWithBLOBs record, @Param("example") NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") NewsOfCompanyWithBLOBs record, @Param("example") NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NewsOfCompany record, @Param("example") NewsOfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsOfCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsOfCompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsOfCompany record);

    /**
     * 获取所有公司的新闻
     * @return
     */
    List<NewsOfCompanyWithBLOBs> selectAllNews(Map<String,Integer> map);

    /**
     * 获取所有新闻的条数
     */
    int countAllNews();
    /**
     * 获取匹配结果的公司的新闻
     * @return
     */
    List<NewsOfCompanyWithBLOBs> selectMatchNews(Map map);
    /**
     * 获取匹配新闻的条数
     */
    int countMatchNews(Map map);
}