package com.scorpion.dao;

import com.scorpion.pojo.*;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NewsOfIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int countByExample(NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int deleteByExample(NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(NewsOfIndustryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int insert(NewsOfIndustryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int insertSelective(NewsOfIndustryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    List<NewsOfIndustryWithBLOBs> selectByExampleWithBLOBs(NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    List<NewsOfIndustry> selectByExample(NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    NewsOfIndustryWithBLOBs selectByPrimaryKey(NewsOfIndustryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NewsOfIndustryWithBLOBs record, @Param("example") NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") NewsOfIndustryWithBLOBs record, @Param("example") NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NewsOfIndustry record, @Param("example") NewsOfIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsOfIndustryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsOfIndustryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table industry_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsOfIndustry record);

    int countAllNews();

    List<NewsOfIndustryWithBLOBs> selectAllNews(Map map);

    List<NewsOfIndustryWithBLOBs> selectMatchNews(Map map);

    /*int countMatchNews(Map map);

    List<String> getIndustryKeywords(Map map);*/

    List<ComNameNewsCount> NewsCount();

    List<ComNameNewsCount> getMatchNewsCount(Map map);
}