package com.scorpion.dao;

import com.scorpion.pojo.Pmi;
import com.scorpion.pojo.PmiExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PmiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int countByExample(PmiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int deleteByExample(PmiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int insert(Pmi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int insertSelective(Pmi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    List<Pmi> selectByExample(PmiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    Pmi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pmi record, @Param("example") PmiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pmi record, @Param("example") PmiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pmi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pmi record);
    /**
     * 获取全国PMI的数据
     * @return
     */
    List<Pmi> selectAllPMI();
}