package com.scorpion.dao;

import com.scorpion.pojo.PolicyOfZmq;
import com.scorpion.pojo.PolicyOfZmqExample;
import com.scorpion.pojo.PolicyOfZmqKey;
import com.scorpion.pojo.PolicyOfZmqWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PolicyOfZmqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int countByExample(PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int deleteByExample(PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PolicyOfZmqKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int insert(PolicyOfZmqWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int insertSelective(PolicyOfZmqWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    List<PolicyOfZmqWithBLOBs> selectByExampleWithBLOBs(PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    List<PolicyOfZmq> selectByExample(PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    PolicyOfZmqWithBLOBs selectByPrimaryKey(PolicyOfZmqKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PolicyOfZmqWithBLOBs record, @Param("example") PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PolicyOfZmqWithBLOBs record, @Param("example") PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PolicyOfZmq record, @Param("example") PolicyOfZmqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PolicyOfZmqWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PolicyOfZmqWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zimaoqu_policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PolicyOfZmq record);

    /**
     * 获取自贸区政策的数量
     * @return
     */
    int countAllZmqPolicy();

    /**
     * 获取所有自贸区政策
     * @param map
     * @return
     */
    List<PolicyOfZmqWithBLOBs> selectAllZmqPolicy(Map<String,Integer> map);
}