package com.scorpion.dao;

import com.scorpion.pojo.Policy;
import com.scorpion.pojo.PolicyExample;
import com.scorpion.pojo.PolicyWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PolicyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int countByExample(PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int deleteByExample(PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int insert(PolicyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int insertSelective(PolicyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    List<PolicyWithBLOBs> selectByExampleWithBLOBs(PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    List<Policy> selectByExample(PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    PolicyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PolicyWithBLOBs record, @Param("example") PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") PolicyWithBLOBs record, @Param("example") PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Policy record, @Param("example") PolicyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PolicyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PolicyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Policy record);

    /**
     * 根据按钮来查询不同类别的政策新闻的数量
     * @param map
     * @return
     */
    int countPolicyByCat(Map map);

    /**
     * 根据按钮来查询不同类别的自贸区新闻
     * @param map
     * @return
     */
    List<PolicyWithBLOBs> selectPolicyByCat(Map map);
    /**
     * 政策新闻的数量
     * @return
     */
    int countPolicyNews();

    /**
     * 所有政策新闻
     * @param map
     * @return
     */
    List<PolicyWithBLOBs> selectPolicyNews(Map map);

    int countMatchPolicyNews(Map map);
    List<PolicyWithBLOBs> selectMatchPolicyNews(Map map);
}