package com.scorpion.dao;

import com.scorpion.pojo.TotalRetailSalesOfConsumerGoods;
import com.scorpion.pojo.TotalRetailSalesOfConsumerGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TotalRetailSalesOfConsumerGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int countByExample(TotalRetailSalesOfConsumerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int deleteByExample(TotalRetailSalesOfConsumerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int insert(TotalRetailSalesOfConsumerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int insertSelective(TotalRetailSalesOfConsumerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    List<TotalRetailSalesOfConsumerGoods> selectByExample(TotalRetailSalesOfConsumerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    TotalRetailSalesOfConsumerGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TotalRetailSalesOfConsumerGoods record, @Param("example") TotalRetailSalesOfConsumerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TotalRetailSalesOfConsumerGoods record, @Param("example") TotalRetailSalesOfConsumerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TotalRetailSalesOfConsumerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_retail_sales_of_consumer_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TotalRetailSalesOfConsumerGoods record);

    /**
     * 获取全国TotalRetailSalesOfConsumerGoods的数据
     * @return
     */
    List<TotalRetailSalesOfConsumerGoods> selectAllTRSC();
}