package com.scorpion.dao;

import com.scorpion.pojo.ZmqEvent;
import com.scorpion.pojo.ZmqEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZmqEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int countByExample(ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int deleteByExample(ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int insert(ZmqEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int insertSelective(ZmqEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    List<ZmqEvent> selectByExampleWithBLOBs(ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    List<ZmqEvent> selectByExample(ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    ZmqEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZmqEvent record, @Param("example") ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ZmqEvent record, @Param("example") ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZmqEvent record, @Param("example") ZmqEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZmqEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ZmqEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zmq_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZmqEvent record);

    List<ZmqEvent> queryZmqEvent(String name);
}